version: '2'

services:

### Application Code Container ##############################
    volumes_source:
        build: ./volumes/application
        volumes:
            - ../:/var/www


### Databases Data Container ################################
    volumes_data:
        build: ./volumes/data
        volumes:
            - /var/lib/mysql:/var/lib/mysql
            - /var/lib/postgres:/var/lib/postgres
            - /var/lib/mariadb:/var/lib/mariadb
            - /var/lib/memcached:/var/lib/memcached
            - /var/lib/redis:/data
            - /var/lib/neo4j:/var/lib/neo4j/data
            - /var/lib/mongo:/data/db


### Workspace Utilities Container ###########################
    workspace:
        build:
            context: ./workspace
        volumes_from:
            - volumes_source
        tty: true


### Nginx Server Container ##################################
    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
