version: '2'

services:

### Application Code Container ##############################
    volumes_source:
        build: ./volumes/application
        volumes:
            - ../:/var/www/app
            - ./volumes/log/nginx:/var/log/nginx
            - node_modules:/var/www/app/node_modules


### Databases Data Container ################################
    volumes_data:
        build: ./volumes/data
        volumes:
            - /.db/mariadb:/var/lib/mysql


### Workspace Utilities Container ###########################
    workspace:
        build: ./workspace
        volumes_from:
            - volumes_source
        links:
            - mariadb
        tty: true


### Nginx Server Container ##################################
    nginx:
        build: ./nginx
        volumes_from:
            - volumes_source
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm
            - node-app


### PHP-FPM Container #######################################
    php-fpm:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile-70
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        links:
            - workspace


### Node Service Container ##################################
    node-app:
        build: ./node
        volumes_from:
            - volumes_source
        expose:
            - "3000"
        links:
            - workspace


### MariaDB Container #######################################
    mariadb:
        build: ./mariadb
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root


### USER - twitter_reader.js ################################
    twitter_reader.js:
        build: ./node
        command: ["nodemon", "-L", "app/services/twitter_reader.js"]
        volumes_from:
            - volumes_source


### USER - twitter_publisher.js #############################
    twitter_publisher.js:
        build: ./node
        command: ["nodemon", "-L", "app/services/twitter_publisher.js"]
        volumes_from:
            - volumes_source



volumes:
    node_modules:
