version: '2'

services:

### Databases Data Container ################################

    volumes_data:
        build: ./volumes/data
        volumes:
            - /var/lib/mysql:/var/lib/mysql
            - /var/lib/postgres:/var/lib/postgres
            - /var/lib/mariadb:/var/lib/mariadb
            - /var/lib/memcached:/var/lib/memcached
            - /var/lib/redis:/data
            - /var/lib/neo4j:/var/lib/neo4j/data
            - /var/lib/mongo:/data/db

### Nginx Server Container ##################################

    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
